create table public.customer (
	id uuid not null,
	archived boolean,
	archived_at timestamp with time zone,
	birth_date date,
	created_by_user_id uuid,
	document varchar(255),
	email varchar(255),
	first_name varchar(255),
	last_modified_at timestamp with time zone,
	last_modified_by_user_id uuid,
	last_name varchar(255),
	loyalty_points integer,
	phone varchar(255),
	promotion_notifications_allowed boolean,
	registered_at timestamp with time zone,
	address_city varchar(255),
	address_complement varchar(255),
	address_neighborhood varchar(255),
	address_number varchar(255),
	address_state varchar(255),
	address_street varchar(255),
	address_zip_code varchar(255),
	version bigint,
	constraint uq_contact_email unique (email),
	primary key (id)
);